// <auto-generated />
using System;
using FitnessTicketApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTicketApp.Migrations
{
    [DbContext(typeof(MVCDbContext))]
    [Migration("20230511094621_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessTicketApp.Models.Domain.BerletTipus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ar")
                        .HasColumnType("int");

                    b.Property<int>("HanyBelepesreErvenyes")
                        .HasColumnType("int");

                    b.Property<int>("HanyNapigErvenyes")
                        .HasColumnType("int");

                    b.Property<int>("Hanyoraig")
                        .HasColumnType("int");

                    b.Property<int>("Hanyoratol")
                        .HasColumnType("int");

                    b.Property<string>("Megnevezes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NapontaHanyszorHasznalhato")
                        .HasColumnType("int");

                    b.Property<int>("Terem_Id")
                        .HasColumnType("int");

                    b.Property<bool>("Torolve")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BerletTipusok");
                });
#pragma warning restore 612, 618
        }
    }
}
